### ISSUE TITLE
Arduino Remote Connection Setup

### ISSUE THREAD

**Issue by onurcakmakceng** [onurd-ck/arduino-wake-on-lan-cloudmq#1]
We can use secure+free MQTT (with SSL) (MQTTS). Like Flespi MQQT Broker and Adafruit MQTT Library. Additional information:
- https://medium.com/@flespi/how-to-connect-esp8266-to-secure-mqtt-broker-know-it-all-and-get-it-done-approach-c33b94f37d88
- https://flespi.com/mqtt-broker
- https://flespi.com/mqtt-broker#client
- https://github.com/flespi-software/ESP8266_mqtts
- https://github.com/adafruit/Adafruit_MQTT_Library
- https://io.adafruit.com/ (Search Keywords: Adafruit MQTT)
- https://learn.adafruit.com/adafruit-io/mqtt-api

**Comment by onurcakmakceng** [comment]
Altenartives:
- GCP IoT (has free tier up to 500mb/month)
- Amazon IoT  - not free

**Comment by onurcakmakceng** [comment]
There is TLS support/processor in only Wifi module (ESP8266) not in Ethernet module (ESP32) or shield (w5100). You can use TLS with 'WifiClientSecure' library (only for Wifi modules/shields)  but could not use 'EthernetClient' library (There is no support for TLS). Flespi.io (with Adafruit MQ) supports TLS but in their sample code they used 'WifiClientSecure' structure.

https://forum.arduino.cc/index.php?topic=608163.0
https://github.com/esp8266/Arduino/issues/3277
https://forum.arduino.cc/index.php?topic=17540.0

What a disappointment!

![image](https://user-images.githubusercontent.com/28986277/65726367-8ec18a00-e0bd-11e9-8ec1-4df5fde548c2.png)

**Comment by d-a-v** [comment]
We can have TLS over Ethernet on esp8266/arduino
